### ISSUE TITLE
大脚 API

### ISSUE THREAD

**Issue by yy0c** [sonofsky2010/SKBigFoot#1]
为了能在 Linux 下直接更新大脚，我想写一个 Python 版本的大脚更新工具，所以想到你的代码中找找相关的数据。但是我对 Mac 上的程序不熟悉，能告诉我应该参考哪些部分吗？

**Comment by sonofsky2010** [comment]
看那些URL是怎么得到的，首先会下个filelist，filelist有插件的下载地址和hash值，下载回来的文件是zip格式，需要解压
